server:
  port: 8189
  servlet:
    context-path: /worker-back
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/worker
    username: worker
    password: singularitypassword
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect



